### ISSUE TITLE
Error in loading data when running bloodstream on a single subject

### ISSUE THREAD

**Issue by mnoergaard** [mathesong/bloodstream#17]
I get an error related to loading of the data when running bloodstream on a single subject. 

![Skærmbillede 2024-08-26 kl  13 12 06](https://github.com/user-attachments/assets/24da498e-ecd7-4104-b6e3-e6a5e25cc707)

The error goes away and bloodstream runs when duplicating the subject data so there now two subjects.

**Comment by mathesong** [comment]
Solved.
