### ISSUE TITLE
Output AIF not fully specified across all time when autosampler data is present

### ISSUE THREAD

**Issue by mnoergaard** [mathesong/bloodstream#18]
I tried to run bloodstream on 18F-VAT data from Stonybrook. It has 6 minutes of autosampler data available (whole blood) and also manual sampling starting at 2 minutes, and then up until scan end (150 minutes) with both total plasma, whole blood and metabolite data. When trying to run bloodstream it finishes, however, the modeled output data (inputfunction.tsv) file only contains data for the time period of the automatic sampling, and not the remaining part of the data.

<img width="986" alt="Skærmbillede 2024-08-26 kl  1 35 31 PM" src="https://github.com/user-attachments/assets/5d1218de-98c6-49ed-9b95-c28042a1b06b">
<img width="981" alt="Skærmbillede 2024-08-26 kl  1 35 52 PM" src="https://github.com/user-attachments/assets/aaabdc06-88cd-4bce-b691-742e8c7f356c">
<img width="1120" alt="Skærmbillede 2024-08-26 kl  1 36 00 PM" src="https://github.com/user-attachments/assets/9591ccda-870d-4609-a1b2-e4325a521524">
<img width="1050" alt="Skærmbillede 2024-08-26 kl  1 36 12 PM" src="https://github.com/user-attachments/assets/97f2b2a0-fbac-4ea3-997a-9c1c71d561ab">

**Comment by mathesong** [comment]
This is extremely weird: I've never encountered this.  Could you maybe send me a mini sample dataset to play with and I'll try to figure out what's going wrong...

**Comment by mathesong** [comment]
This was caused by the blood_discrete data being specified in minutes, but with Units="s".  So bloodstream assumes that it's a very short acquisition. I've added a new QC check that should pick this up in future.

**Comment by mnoergaard** [comment]
Thanks for catching this mistake from my side, @mathesong !
